FROM node:16.10.0-alpine3.13 as build
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY ./package.json /frontend/
COPY ./yarn.lock /frontend/
RUN yarn
COPY . /frontend
RUN yarn build
CMD ["yarn", "start"]

